name: what_if
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  animated_splash_screen: ^1.3.0
  audioplayers: ^6.0.0
  cached_network_image: ^3.4.0
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.5.0+1
  easy_localization: ^3.0.7
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_bounceable: ^1.1.0
  get_it: ^7.7.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  # assets:
  assets:
    - assets/images/
    - assets/translations/
    - assets/sounds/

  # fonts:
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf

    - family: Moul
      fonts:
        - asset: assets/fonts/Moul-Regular.ttf

    - family: Shrikhand
      fonts:
        - asset: assets/fonts/Shrikhand-Regular.ttf

    - family: ZenDots
      fonts:
        - asset: assets/fonts/ZenDots-Regular.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Italic.ttf

    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/NotoSansArabic_Condensed-Bold.ttf
        - asset: assets/fonts/NotoSansArabic_Condensed-Medium.ttf
        - asset: assets/fonts/NotoSansArabic_Condensed-Regular.ttf


    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal-Regular.ttf
